name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
   
    - name: npm install, build, lint and test
      run: |
        npm install
        npm run build --if-present
        npm run lint
      working-directory: ./colors
    
    - name: Cypress run
      uses: cypress-io/github-action@v1
      with:
        working-directory: ./colors
        start: npm start
        wait-on: http://localhost:3000
        run: npm run test
      env:
        CI: true
